<div class="cm-notification-container"></div>
<?=$vars['message']?>
<div>
	<div class="clear mainbox-title-container">
		<h1 class="mainbox-title">Новая валюта:&nbsp;</h1>
	</div>
	<div class="extra-tools"></div>
	<div class="mainbox-body"> 
		<div class="cm-tabs-content">
			<form class="cm-form-highlight cm-check-changes" name="page_update_form" method="post" action="">
				<div id="content_basic" style="display: block;">
					<fieldset>
						<h2 class="subheader"> Информация </h2>
						<div class="form-field">
							<label class="cm-required" for="page">Название:</label>
							<input type="text" class="input-text-large main-input" value="" style="width:200px;" name="comment" />
						</div>
						<div class="form-field">
							<label class="cm-required" for="page">Префикс <i  style="color:#FF0000;">(2 символа)</i>:</label>
							 <div style="float:left;"><?=Select_masiv($vars['Language'],'language',0,'style="width:208px; "  onChange="EditImag(this.value)" ');?></div> <div style=" padding:5px;float:left;" id="EditImag"></div>
						</div>  
					</fieldset>
				</div>
				<div class="buttons-container cm-toggle-button buttons-bg">
					<div class="cm-buttons-floating hidden" style="display: block;">
						<div class="cm-buttons-placeholder">
							<span class="submit-button cm-button-main">
								<input type="submit" value="Создать" name="add" />
							</span>&nbsp;
							<span class="submit-button cm-button-main cm-save-and-close">
								<input type="submit" value="Создать и закрыть" name="add_close" class="cm-save-and-close" />
							</span> &nbsp;или&nbsp;&nbsp; 
							<a class="underlined tool-link" href="/admin/<?=$vars['action']?>">Отменить</a>
						</div>
					</div>
				</div>
				<input type="hidden" value="<?=$vars['action']?>" id="action" />
			</form>
		</div>
	</div>
</div>
<script type="text/javascript">
function EditImag(val){
	$('#EditImag').html('<img src="/tpl/admin/images/flags/'+val+'.png" />');
 	
	
}
</script>