<tr class="noDrop">
    <th width="25"></th>
    <th width="20" class="center"><input type="checkbox" class="check_all2" title="Отметить/снять все" value="Y" name="check_all"></th>
    <th width="20">ID</th>
    <th width="50">Фото</th>
    <th>Название</th>
    <th width="100">Статус</th>
    <th width="80">&nbsp;</th>
    </tr>
    <?php
    $dir=createDir($vars['id']);
    foreach($vars['photo'] as $row)
    {
        if($row['active']==1)$active='<div class="selected-status status-a"><a> Вкл. </a></div>';
        else $active='<div class="selected-status status-d"><a> Выкл. </a></div>';

        echo'<tr id="sort'.$row['id'].'">
				<td class="move"></td>
				<td class="center"><input type="checkbox" class="check-item" value="'.$row['id'].'" name="photo_id[]" /></td>
				<td><span>'.$row['id'].'</span></td>
				<td><img src="/'.$dir['1'].$row['id'].'_s.jpg" alt="" width="50" /></td>
				<td><input type="text" value="'.$row['name'].'" name="photo_name[]" class="input-text"></td>
				<td><input type="hidden" value="'.$row['id'].'" name="save_photo_id[]" />
					<div cslass="select-popup-container active_status" id="active'.$row['id'].'">'.$active.' </div>
				</td>
				<td width="10%">
					<ul class="cm-tools-list tools-list">
						<li><a href="/admin/product/edit/'.$row['product_id'].'/delete/'.$row['id'].'" class="cm-confirm">Удалить</a></li>
					</ul>
				</td>
			</tr>';
    }
    ?>