<div id="feedback_other">
    <h3>Вы можете задать вопрос, заполнив простую форму:</h3>
	<div id="message"></div>
    <form method="post" onsubmit="return sendFeedback();">
		<div style="width:250px; float:left; margin-right:25px;">
			<input type="text" name="f_name" id="f_name" value="<?=$vars['translate']['name']?>" />
			<input type="text" name="f_name" id="f_email" value="<?=$vars['translate']['email']?>" />
			<input type="text" name="f_phone" id="f_phone" value="<?=$vars['translate']['phone']?>" />
		</div>
		<div style="width:412px; float:left;">
			<textarea rows="5" cols="35" name="f_message" id="f_message"><?=$vars['translate']['message']?></textarea>
			<div style="text-align:right;">
				<input type="button" value="Очистить форму" onClick="this.form.reset()" />
				<input type="submit" name="f_submit" value="<?=$vars['translate']['send_message']?>" class="submit" />
			</div>
		</div>
		<div class="clear"></div>
    </form>
</div>