<?
	$i=0;
	$half1='';
	$half2='';
	$cnt=count($vars['menu'])-1;
	foreach($vars['menu'] as $row)
	{
		if($i==0)$style=' id="first"';
		elseif($i==$cnt)$style=' id="last"';
		else $style='';
		
		$pos = strpos($row['url'], "http://");
		if($pos !== false)$link=$row['url'].'" target="_blank" rel="nofollow';
		elseif($row['url']=="/")$link=$row['url'];
		else $link="/".$row['url'];
	   
		if($i<3)
		{
			$half1.='<li'.$style.'';if($_SERVER['REQUEST_URI']==$link)$half1.=' class="cur_menu"';$half1.='><a href="'.$link.'">'.$row['name'].'</a></li>';
		}
		else{
			$half2.='<li'.$style.'';if($_SERVER['REQUEST_URI']==$link)$half2.=' class="cur_menu"';$half2.='><a href="'.$link.'">'.$row['name'].'</a></li>';
		}
		$i++;
	}
?>

<div id="top_right">
	<div style="height:43px;">
		<?=htmlspecialchars_decode($vars['phone']['body']);?>
	</div>
	<div class="menu">
		<ul>
			<?=$half1?>
			<div class="clear"></div>
		</ul>
	</div>
</div>
<div id="logo"><a href="/"><img src="/tpl/column1/images/logo.png" alt="" /></a></div>
<div id="cart">
	<div id="bascket"></div>
	<div class="menu">
		<ul>
			<?=$half2?>
			<div class="clear"></div>
		</ul>
	</div>
</div>
<div class="clear"></div>